const icons = {
  Handshake: require("../../assets/images/dashboard/choosePlay/handshake.png"),
  Die: require("../../assets/images/dashboard/choosePlay/die.png"),
  Dice: require("../../assets/images/dashboard/games/dice.png"),
  Draught: require("../../assets/images/dashboard/games/draught.png"),
  Monopoly: require("../../assets/images/dashboard/games/monopoly.png"),
  Chess: require("../../assets/images/dashboard/games/chess.png"),
  Scramble: require("../../assets/images/dashboard/games/scrabble.png"),
  facebook: require("../../assets/images/facebook.png"),
  google: require("../../assets/images/google.png"),
  leftArrow: require("../../assets/images/leftArrow.png"),
  message: require("../../assets/images/chessGame/Message.png"),
  flag: require("../../assets/images/chessGame/flag.png"),
  theme1: require("../../assets/images/chessGame/theme1.png"),
  theme2: require("../../assets/images/chessGame/theme2.png"),
  theme3: require("../../assets/images/chessGame/theme3.png"),
  playopt1: require("../../assets/images/chessGame/playopt1.png"),
  playopt2: require("../../assets/images/chessGame/playopt2.png"),
  playopt3: require("../../assets/images/chessGame/playopt3.png"),
  queen: require("../../assets/images/chessGame/purpleQueen.png"),
  knight: require("../../assets/images/chessGame/purpleKnight.png"),
  bishop: require("../../assets/images/chessGame/purpleBishop.png"),
  rook: require("../../assets/images/chessGame/rookPurple.png"),
  wallet:require("../../assets/images/navigation/Wallet.png"),
  user2:require("../../assets/images/navigation/user2.png"),
  user:require("../../assets/images/navigation/user.png"),
  home2:require("../../assets/images/navigation/home2.png"),
  home:require("../../assets/images/navigation/home.png"),
  dashboard:require("../../assets/images/profileMenu/dashboard.png"),
  profile:require("../../assets/images/profileMenu/profile.png"),
  friends:require("../../assets/images/profileMenu/friends.png"),
  watch:require("../../assets/images/profileMenu/watch.png"),
  rules:require("../../assets/images/profileMenu/rules.png"),
  help:require("../../assets/images/profileMenu/help.png"),
  learn:require("../../assets/images/profileMenu/learn.png"),
  overlayboard:require("../../assets/images/stakecoin/overlayBoard.png")
};

export default icons;
